package com.connecttopcvr.phone;
import android.app.*;import android.os.*;import android.graphics.*;import android.view.*;import android.content.*;import android.widget.*;import java.net.*;import java.util.*;
public class MainActivity extends Activity{
 PCView v; public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);v=new PCView(this);setContentView(v);new Handler().postDelayed(()->ip(),200);}
 void ip(){EditText e=new EditText(this);e.setSingleLine();e.setText("192.168.1.20");new AlertDialog.Builder(this).setTitle("Connect to PC").setMessage("Одна Wi-Fi сеть, порт 48150").setView(e).setPositiveButton("CONNECT",(d,w)->v.connect(e.getText().toString().trim())).show();}
 static class PCView extends View{
  Paint p=new Paint(3),t=new Paint(3); DatagramSocket s; String host=""; boolean run=false,screenTouch=false; Bitmap bmp; float sx,sy,sw,sh; int seq=-1,got;byte[][] parts;byte[] magic="PCVR1".getBytes();
  String[] labs={"ESC","1","2","3","4","5","6","7","8","9","0","BACK","TAB","Q","W","E","R","T","Y","U","I","O","P","CAPS","A","S","D","F","G","H","J","K","L","ENTER","SHIFT","Z","X","C","V","B","N","M",",",".","SHIFT"};
  String[] keys={"esc","1","2","3","4","5","6","7","8","9","0","backspace","tab","q","w","e","r","t","y","u","i","o","p","capslock","a","s","d","f","g","h","j","k","l","enter","shift","z","x","c","v","b","n","m",",",".","shift"};
  PCView(Context c){super(c);t.setTypeface(Typeface.DEFAULT_BOLD);}
  void connect(String h){host=h;run=true;new Thread(()->net()).start();invalidate();}
  void net(){try{s=new DatagramSocket();s.setSoTimeout(1000);send("HELLO PCVR1");byte[] b=new byte[65535];while(run){try{DatagramPacket d=new DatagramPacket(b,b.length);s.receive(d);if(d.getLength()<13||!same(b,0,magic))continue;int q=ri(b,5),i=rs(b,9),n=rs(b,11);if(q!=seq||parts==null||parts.length!=n){seq=q;parts=new byte[n][];got=0;}if(i<n&&parts[i]==null){parts[i]=Arrays.copyOfRange(b,13,d.getLength());got++;}if(got==n){int z=0;for(byte[] x:parts)z+=x.length;byte[] jpg=new byte[z];int o=0;for(byte[] x:parts){System.arraycopy(x,0,jpg,o,x.length);o+=x.length;}bmp=BitmapFactory.decodeByteArray(jpg,0,z);parts=null;postInvalidate();}}catch(Exception e){}}}catch(Exception e){}}
  int ri(byte[] b,int o){return (b[o]&255)<<24|(b[o+1]&255)<<16|(b[o+2]&255)<<8|(b[o+3]&255);}int rs(byte[] b,int o){return (b[o]&255)<<8|(b[o+1]&255);}boolean same(byte[]a,int o,byte[]m){for(int i=0;i<m.length;i++)if(a[o+i]!=m[i])return false;return true;}
  synchronized void send(String x){try{byte[]b=x.getBytes();s.send(new DatagramPacket(b,b.length,InetAddress.getByName(host),48150));}catch(Exception e){}}
  void mouse(float x,float y){send(String.format(Locale.US,"INPUT MOUSE %.4f %.4f",x,y));}void click(){send("INPUT CLICK left");}void key(String k){send("INPUT KEY "+k);}
  protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();p.setColor(Color.rgb(7,10,16));c.drawRect(0,0,w,h,p);p.setColor(Color.rgb(25,29,38));c.drawRect(0,h*.72f,w,h,p);box(c,w*.1f,h*.61f,w*.8f,h*.12f,18,Color.rgb(76,49,31));sw=w*.66f;sh=h*.43f;sx=(w-sw)/2;sy=h*.09f;box(c,sx-10,sy-10,sw+20,sh+20,10,Color.DKGRAY);if(bmp!=null)c.drawBitmap(bmp,null,new RectF(sx,sy,sx+sw,sy+sh),p);else{p.setColor(Color.rgb(10,17,25));c.drawRect(sx,sy,sx+sw,sy+sh,p);t.setTextSize(28);t.setColor(Color.WHITE);c.drawText(run?"Ожидание экрана ПК":"Введи IP компьютера",sx+20,sy+sh/2,t);}box(c,w*.69f,h*.49f,w*.13f,h*.21f,8,Color.rgb(24,27,33));box(c,w*.45f,h*.52f,w*.1f,h*.11f,5,Color.GRAY);keyboard(c,w*.21f,h*.63f,w*.38f,h*.15f);t.setTextSize(20);t.setColor(Color.WHITE);c.drawText(run?"CONNECTED  "+host:"NOT CONNECTED",16,h-16,t);}
  void box(Canvas c,float x,float y,float w,float h,float d,int col){p.setColor(col);c.drawRect(x,y,x+w,y+h,p);p.setColor(Color.rgb(Math.max(0,Color.red(col)-25),Math.max(0,Color.green(col)-25),Math.max(0,Color.blue(col)-25)));Path q=new Path();q.moveTo(x+w,y);q.lineTo(x+w+d,y+d);q.lineTo(x+d,y+h+d);q.lineTo(x,y+h);q.close();c.drawPath(q,p);}
  void keyboard(Canvas c,float x,float y,float w,float h){p.setColor(Color.rgb(20,23,29));c.drawRoundRect(x,y,x+w,y+h,10,10,p);float g=3,rh=h/5f;int k=0;for(int r=0;r<4;r++){int n=r==0?12:11;float cw=(w-(n+1)*g)/n,xx=x+g,yy=y+g+r*rh;for(int i=0;i<n;i++){float ww=cw;String lab=labs[k];if(lab.equals("BACK")||lab.equals("ENTER")||lab.equals("SHIFT")||lab.equals("CAPS")||lab.equals("TAB"))ww*=1.3;p.setColor(Color.rgb(48,53,64));c.drawRoundRect(xx,yy,xx+ww,yy+rh-g,4,4,p);t.setTextSize(11);t.setColor(Color.LTGRAY);c.drawText(lab,xx+3,yy+rh*.62f,t);xx+=ww+g;k++;}}p.setColor(Color.rgb(48,53,64));c.drawRoundRect(x+w*.25f,y+4*rh+g,x+w*.75f,y+h-g,4,4,p);t.setTextSize(12);t.setColor(Color.WHITE);c.drawText("SPACE",x+w*.46f,y+h-8,t);}
  public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();if(e.getAction()==0){screenTouch=x>=sx&&x<=sx+sw&&y>=sy&&y<=sy+sh;if(screenTouch)mouse((x-sx)/sw,(y-sy)/sh);return true;}if(e.getAction()==2&&screenTouch){mouse(cl((x-sx)/sw),cl((y-sy)/sh));return true;}if(e.getAction()==1){if(screenTouch){mouse(cl((x-sx)/sw),cl((y-sy)/sh));click();screenTouch=false;return true;}keyAt(x,y);return true;}return true;}
  float cl(float x){return Math.max(0,Math.min(1,x));}
  void keyAt(float x,float y){float kx=getWidth()*.21f,ky=getHeight()*.63f,kw=getWidth()*.38f,kh=getHeight()*.15f;if(x<kx||x>kx+kw||y<ky||y>ky+kh)return;float rh=kh/5f,g=3;int r=(int)((y-ky)/rh);if(r==4){key("space");return;}int n=r==0?12:11,idx=r==0?0:(r==1?12:(r==2?23:34));float cw=(kw-(n+1)*g)/n,xx=kx+g,yy=ky+g+r*rh;for(int i=0;i<n;i++){String lab=labs[idx+i];float ww=cw;if(lab.equals("BACK")||lab.equals("ENTER")||lab.equals("SHIFT")||lab.equals("CAPS")||lab.equals("TAB"))ww*=1.3;if(x>=xx&&x<=xx+ww&&y>=yy&&y<=yy+rh-g){key(keys[idx+i]);return;}xx+=ww+g;}}
 }
}
